swagger: "2.0"
info:
  description: "API document for Rocket BlueZone Web"
  version: "1.0.0"
  title: "Rocket BlueZone Shared APIs"
  contact:
    email: "jgao@rocketsoftware.com"
  license:
    name: "Rocket Software Commercial License"
host: "rs28:30004"
basePath: "/ZLUX/plugins/com.rs.bzshared/services"
tags:
- name: "BZShared"
  description: "Web based terminal emulation product by Rocket Software"
  externalDocs:
    description: "Find out more"
    url: "https://www.rocketsoftware.com/products/rocket-bluezonepassport-terminal-emulator"
- name: "userResource"
  description: "Rocket BlueZone Web API"
- name: "userPrivilege"
  description: "Rocket BlueZone Web API"
schemes:
- "https"
- "http"
paths:
  /shareSession:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "Share Session"
      operationId: "shareSession"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"

  /unshareSession:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "Unshare Session"
      operationId: "unshareSession"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"

  /sessions:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "sessions"
      operationId: "getSessions"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
  /sessionPrivate:
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "sessionPrivate"
      operationId: "deleteSessionPrivate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "sessionPrivate"
      operationId: "createSessionPrivate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
            
  /sessionShared:
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "sessionShared"
      operationId: "deleteSessionShared"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "sessionShared"
      operationId: "createSessionShared"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"

  /keyboardMapping:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "keyboardMapping"
      operationId: "getKeyboardMapping"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "keyboardMapping"
      operationId: "deleteKeyboardMapping"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "keyboardMapping"
      operationId: "createKeyboardMapping"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
  /hotspot:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "hotspot"
      operationId: "getHotspot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "hotspot"
      operationId: "deleteHotspot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "hotspot"
      operationId: "createHotspot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
  /launchpad:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "launchpad"
      operationId: "getLaunchpad"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "launchpad"
      operationId: "deleteLaunchpad"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "launchpad"
      operationId: "createLaunchpad"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
  /preference:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "preference"
      operationId: "getPreference"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    delete:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "preference"
      operationId: "deletePreference"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "preference"
      operationId: "createPreference"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
          
  /script3270:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "script3270"
      operationId: "getScript3270"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
          
  /script5250:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "script5250"
      operationId: "getScript5250"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"
    
  /scriptvt:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "scriptvt"
      operationId: "getScriptvt"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
          
  /script:
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "script"
      operationId: "createScript"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
          
  /scripteditor:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "scripteditor"
      operationId: "getScripteditor"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
    put:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "scripteditor"
      operationId: "putScripteditor"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
          
  /defaults:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "Defaults"
      operationId: "getDefaults"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
          
  /trustedhosts/3270:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "trustedhosts"
      operationId: "getTrustedhosts3270"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"      
          
  /trustedhosts/5250:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "trustedhosts"
      operationId: "getTrustedhosts5250"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"   
          
  /healthcheck:
    get:
      tags:
      - "userResource"
      summary: "Rocket BlueZone Web API"
      description: "Health check"
      operationId: "getHealthcheck"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"   
          
          
  /:
    post:
      tags:
      - "userPrivilege"
      summary: "Rocket BlueZone Web API"
      description: "User privilege"
      operationId: "postPrivilege"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
        "400":
          description: "Bad Request"             
          
          
          