swagger: "2.0"
info:
  description: "API document for Rocket BlueZone Web"
  version: "1.0.0"
  title: "Rocket BlueZone Web APIs"
  contact:
    email: "jgao@rocketsoftware.com"
  license:
    name: "Rocket Software Commercial License"
host: "rs28:30004"
basePath: "/ZLUX/plugins/com.rs.bzw/services"
tags:
- name: "BZW"
  description: "Web based terminal emulation product by Rocket Software"
  externalDocs:
    description: "Find out more"
    url: "https://www.rocketsoftware.com/products/rocket-bluezonepassport-terminal-emulator"
- name: "sessionMode"
  description: "Rocket BlueZone Web API"
schemes:
- "https"
- "http"
paths:
  /:
    get:
      tags:
      - "sessionMode"
      summary: "Rocket BlueZone Web API"
      description: "Get Session Mode"
      operationId: "getSessionMode"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Session Mode"
